Add source documentation across the board.
DuetHealth/Kumo pull request #13
Opened 2021-08-19 21:29 UTC by k3zi

2021-08-20 13:55 UTC, powerje commented on Sources/Kumo/Data/MultipartForm.swift
> +            + "--\(boundary)--".data(using: encoding)!
😅

2021-08-20 13:58 UTC, powerje commented on Sources/Kumo/HTTP/HTTPRequest.swift
> +public protocol _RequestMethod { }
These changes are breaking, we should make sure to bump the major version

2021-08-20 13:59 UTC, powerje commented on Sources/Kumo/Kumo.docc/BlobCache.md
> +let blobCache = BlobCache(baseURL: URL(string: "https://www.apple.com")!)
😎

2021-08-20 19:52 UTC, powerje approved these changes

2021-08-20 19:52 UTC, powerje requested changes
Please bump the major version then I think we're good to go

2021-09-02 11:32 UTC, k3zi commented
@powerje 
> Please bump the major version then I think we're good to go
I believe the version is just controlled by the tag.

2021-09-02 12:46 UTC, powerje commented
> 
> 
> I believe the version is just controlled by the tag.
> 
> 

Doh, I thought it was in the podspec as well. Been awhile since I've used Cocoapods 😅

2021-09-02 12:48 UTC, powerje approved these changes

2021-09-03 17:17 UTC, k3zi commented
@powerje No, you're right. I just completely forgot about CocaPods.

2021-09-03 17:17 UTC, merged